language: generic
sudo: required

services:
- docker

before_install:
- docker-compose build web

script:
- docker-compose run web npm run lint

notifications:
  slack:
    secure: R6wugc91DofuEoDCW/va0QclEQo+xmHRxkKhicPs2zB61HbD0KfZbjFMHSPiqqyGl2+wSUiS9gq5f9nZyyhl0KKb/03t0xmVMrU9Q0D8UpnFKe2kQn4sA664pWtzlfN0qi9Qj4ACOsr5AMi6QumDvzzk/DyZvQTMKiTsVSd7PbkYfjhfuVTfOglfjzXSBCofQNlIhuunnGs9vKKXDU0B4CmRj+nm4UssRjdXxmLDHx3H7ecCd6lsjUx79wiSig8l7z2IytHgVUdZ4iHWNUEl7uOIVLynsT3aAFNzhlz8eyQgdgN820bcIDJW+KlMs98VaJWn6kGAfTOFI4AbURJI8bA5uuOkUpfMCaSdeDPL61rCgNoxVyJY9mkIW36i5HSKR3B+cbJ4y862SU3XUb3q6l3rVjOBycc66Jm/7DtDDxIvmnoo4IbpznpUfZKGdQhwrinPQLeoAmN13Ed6hvDrtz5/nD8zAjvppfj1HUMRN/lIE20NXdcXyrwqweD2BhNQoczz5Zu879ec+QdNg/wS66dHsKSToVZspI820gkGt0TeZUBu9idDbUjW1v8Xhg9qGm99L7ciaqNsUPaD0ynZhsfHHbBIdEUoJ8LggosIim74fmsx5IacRTf6lvbiJwkqOGjbLEvhgPBuBLP1vpit80qcjargQpfDhO/8UccamBY=
