version: '2.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=touchdown1!

  yopa:
    image: unbounce/yopa:latest
    command: java -Xms64m -Xmx256m -jar uberjar.jar -c /tmp/yopa-in/config.yml -o /tmp/dev-env-aws-regions-override.xml
    ports:
      - 47195:47195
    volumes:
      - ./yopa-config.yml:/tmp/yopa-in/config.yml:ro

  test:
    build: .
    command: npm test
    environment:
      - API_ENV=test
    volumes:
      - .:/superbowleto
      - /superbowleto/node_modules
    depends_on:
      - postgres
      - yopa
