service: superbowleto

frameworkVersion: ">=1.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  boleto_create:
    handler: dist/boleto.create
    events:
      - http:
          path: /boletos
          method: post

  boleto_index:
    handler: dist/boleto.index
    events:
      - http:
          path: /boletos/
          method: get

  boleto_show:
    handler: dist/boleto.show
    events:
      - http:
          path: /boletos/{id}
          method: get

  boleto_processBoletosToRegister:
    handler: dist/boleto.processBoletosToRegister
    events:
      - schedule: rate(2 minutes)

  boleto_register:
    handler: dist/boleto.register
 